name: prowlarr

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.5.2
    container_name: prowlarr
    restart: unless-stopped
    env_file: [../../common.env]
    volumes:
      - ${STACK_ROOT}/appdata/prowlarr:/config
    networks: [media]
    expose: ["9696"]

networks:
  media:
    external: true
