version: "3.8"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID:-1026}
      - PGID=${PGID:-100}
      - TZ=${TZ:-Europe/Paris}
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ${ROOT_DIR:-/volume1}/data:/data
    devices:
      - /dev/dri:/dev/dri

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ:-Europe/Paris}
    ports:
      - 5055:5055
    volumes:
      - ./config:/app/config
