version: "3.8"

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1026}
      - PGID=${PGID:-100}
      - TZ=${TZ:-Europe/Paris}
      - WEBUI_PORT=8080
    volumes:
      - ./config:/config
      - ${ROOT_DIR:-/volume1}/data:/data
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ:-Europe/Paris}
    ports:
      - 8191:8191
