version: "3.8"

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1026}
      - PGID=${PGID:-100}
      - TZ=${TZ:-Europe/Paris}
    volumes:
      - ./radarr-config:/config
      - ${ROOT_DIR:-/volume1}/data:/data
    ports:
      - 7878:7878

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1026}
      - PGID=${PGID:-100}
      - TZ=${TZ:-Europe/Paris}
    volumes:
      - ./sonarr-config:/config
      - ${ROOT_DIR:-/volume1}/data:/data
    ports:
      - 8989:8989

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1026}
      - PGID=${PGID:-100}
      - TZ=${TZ:-Europe/Paris}
    volumes:
      - ./prowlarr-config:/config
    ports:
      - 9696:9696
  
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1026}
      - PGID=${PGID:-100}
      - TZ=${TZ:-Europe/Paris}
    volumes:
      - ./bazarr-config:/config
      - ${ROOT_DIR:-/volume1}/data:/data
    ports:
      - 6767:6767
