version: '3.8'
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - /volume1/docker/r-apps/sonarr/config:/config
      - /volume1/media/series:/series
      - /volume1/torrents:/torrents
    ports:
      - 8989:8989
    restart: unless-stopped
