version: '3.8'
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - /volume1/docker/r-apps/radarr/config:/config
      - /volume1/media/movies:/movies
      - /volume1/torrents:/torrents
    ports:
      - 7878:7878
    restart: unless-stopped
